spring:
  jpa:
    database: HSQL
    hibernate: 
      ddl-auto: create-drop
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./target/h2db/db/backend;DB_CLOSE_DELAY=-1
    username: root
    password: 
    initialize: false
auth:
  secret: b1e9c150-9cc7-4479-a79a-8f1772a1e9c1
  expires: 604800
  header: Authorization
 
security:
  basic:
    enabled: false 